-- INSERT INTO burgers (burger_name, devoured)
-- VALUES ("The Pounder", false),
--  ("The Heart Attack", false),
--  ("The Smokeshow", false),
--  ("The BBQ Blaster", true),
--  ("The American", true),
--  ("The Clogger", true)
