-- INSERT INTO burgers (burger_name, devoured)
-- VALUES ("The Pounder", false),
--  ("The Heart Attack", false),
--  ("The Italian", false),
--  ("The Smokeshow", false),
--  ("The BBQ Blaster", false),
--  ("The American", false),
--  ("The Clogger", true)
