-- INSERT INTO burgers (burger_name)
-- VALUES ("The Pounder"),
--  ("The Heart Attack"),
--  ("The Italian"),
--  ("The Smokeshow"),
--  ("The BBQ Blaster"),
--  ("The American"),
--  ("The Clogger")